### ISSUE TITLE
Unknown error while getting super tasks: 404 Client Error

### ISSUE THREAD

**Issue by tnttol** [vanhbakaa/Clayton#11]
Unknown error while getting super tasks: 404 Client Error: Not Found for url: https://tonclayton.fun/api/cc82f330-6a6d-4deb-a16b-6a335a67ffa7/tasks/super-tasks

**Comment by vanhbakaa** [comment]
You have been banned because you don't enable avanced anti detection RIP

**Comment by tnttol** [comment]
друг, что ты гонишь?

**Comment by tnttol** [comment]
![photo_2024-11-12_14-42-32](https://github.com/user-attachments/assets/3dd23b87-3931-4e8c-80d2-8f5286802597)
![photo_2024-11-12_14-42-29](https://github.com/user-attachments/assets/2ebeae0e-3915-4f48-b53e-21891738cc05)
