### ISSUE TITLE
please check the error 24

### ISSUE THREAD

**Issue by 0xJhinkz** [vanhbakaa/Clayton#20]
[Clayton] | 2024-12-01 13:07:59 | INFO     | 108 - eva | Doesn't have user agent, Creating...
[Clayton] | 2024-12-01 13:07:59 | INFO     | 1016 - eva | start after 4s
[Clayton] | 2024-12-01 13:08:45 | WARNING  | 24 - Error fetching the base URL: HTTPSConnectionPool(host='tonclayton.fun', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002DECA16B310>, 'Connection to tonclayton.fun timed out. (connect timeout=None)'))
[Clayton] | 2024-12-01 13:08:45 | INFO     | 82 - Could not find any main.js format. Dumping page content for inspection:
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    />
    <title>Clayton</title>
    <script src="https://telegram.org/js/telegram-web-app.js"></script>
    <script type="module" crossorigin src="/assets/index-BXOdEvKW.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-DgWsDA98.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>

[Clayton] | 2024-12-01 13:08:45 | WARNING  | 844 - Detected index js file change. Contact me to check if it's safe to continue: https://t.me/vanhbakaaa
Unclosed client session
client_session: <aiocfscrape.CloudflareScraper object at 0x000002DECA16A080>
Terminate batch job (Y/N)? y

C:\Users\MY PC\Clayton>

**Comment by vanhbakaa** [comment]
it's normal thier server doesn't response
